config/routes.rb
Rails.application.routes.draw do

  root 'main#view'

  scope '/admin' do
    resources :categories do
      resources :sub_categories, path: '/subcategories' do
        resources :sub_sub_categories, path: '/subsubcategories' do
          resources :products
        end
      end
    end
  end

  get '(/:cat(/:subcat(/:subsubcat)))' => 'main#view'
  

end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
	# Associations
	belongs_to :category
	has_many :sub_sub_categories, dependent: :destroy
	has_many :products, through: :sub_sub_categories

  	# Validations
	validates :name, presence: true
	validates :name, length: { in: 3..25 }
	validates :name, uniqueness: true
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  
  def show
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:id])
  end

  def new
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.new
  end  

  def create
    @category = Category.find(params[:category_id])
    @sub_category = @category.sub_categories.new(sub_category_params)

    if @sub_category.save
      redirect_to category_sub_category_path(@category, @sub_category)
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:id])

    if @sub_category.update(sub_category_params)
      redirect_to category_sub_category_path(@category, @sub_category)
    else
      render 'edit'
    end

  end

  def destroy
    @category = Category.find(params[:category_id])
    @sub_category = SubCategory.find(params[:id])
    @sub_category.destroy

    redirect_to @category
  end

  private

  def sub_category_params
    params.require(:sub_category).permit(:name)
  end

end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.erb
<%= form_for ([@category, @sub_category]) do |f| %>
	<% if @sub_category.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@sub_category.errors.count, "error") %> prohibited
				this article from being saved:
			</h2>
			<ul>
				<% @sub_category.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.submit class: "btn btn-primary"%>
	</div>
<% end %>

<%= link_to 'Back', category_path(@category), class: "btn btn-default" %>

app/views/sub_categories/edit.html.erb
<%= render 'layouts/header' %>
<div class="container">
	<h1>Edit Sub Category Page</h1>
	<%= render 'form' %>
</div>

app/views/sub_categories/new.html.erb
<%= render 'layouts/header' %>
<div class="container">
	<h1>Add Sub Category Page</h1>
	<%= render 'form' %>
</div>

app/views/sub_categories/show.html.erb
<%= render 'layouts/header' %>
<div class="container">
	<h1>Sub Category</h1>
	<table class="table table-bordered">
		<tr>
			<th>#</th>
			<td><%= @sub_category.id %></td>
		</tr>
		<tr>
			<th>Name</th>
			<td><%= @sub_category.name %></td>
		</tr>
		<tr>
			<th>Category ID</th>
			<td><%= @sub_category.category_id %></td>
		</tr>
		<tr>
			<th>Created At</th>
			<td><%= @sub_category.created_at %></td>
		</tr>
		<tr>
			<th>Updated at</th>
			<td><%= @sub_category.updated_at %></td>
		</tr>
	</table>
	
	<h3>Sub Sub Categories </h3>
	
	<%= link_to 'Add new sub sub category', new_category_sub_category_sub_sub_category_path(@category, @sub_category), class: "btn btn-primary btn-add" %>

	<table class="table table-bordered">
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Actions</th>
		</tr>
		<% @sub_category.sub_sub_categories.each do |sub_sub_category| %>
			<tr>
				<td><%= sub_sub_category.id %></td>
				<td><%= sub_sub_category.name %></td>
				<td>
					<%= link_to 'Show', category_sub_category_sub_sub_category_path(@category, @sub_category, sub_sub_category), class: "btn btn-success" %>
					<%= link_to 'Edit', edit_category_sub_category_sub_sub_category_path(@category, @sub_category, sub_sub_category), class: "btn btn-info" %>
					<%= link_to 'Delete', category_sub_category_sub_sub_category_path(@category, @sub_category, sub_sub_category), class: "btn btn-danger",
					method: :delete,
					data: {confirm: 'Are you sure you want to delete?'} %>
					<%= link_to 'Product page', category_sub_category_sub_sub_category_products_path(@category, @sub_category, sub_sub_category), class: "btn btn-default" %>
				</td>
			</tr>
		<% end %>
	</table>

	<%= link_to 'Back', category_path(@category), class: "btn btn-default" %>
</div>