config/routes.rb
Rails.application.routes.draw do

  root 'main#view'

  scope '/admin' do
    resources :categories do
      resources :sub_categories, path: '/subcategories' do
        resources :sub_sub_categories, path: '/subsubcategories' do
          resources :products
        end
      end
    end
  end

  get '(/:cat(/:subcat(/:subsubcat)))' => 'main#view'
  

end

app/models/category.rb
class Category < ActiveRecord::Base
	# Associations
	has_many :sub_categories, dependent: :destroy
	has_many :products, through: :sub_categories

	# Validations
	validates :name, presence: true
	validates :name, length: { in: 3..25 }
	validates :name, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		@categories = Category.all
	end

	def show
		@category = Category.find(params[:id])
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			redirect_to @category
		else
			render 'new'
		end
	end

	def edit
		@category = Category.find(params[:id])
	end

	def update
		@category = Category.find(params[:id])

		if @category.update(category_params)
			redirect_to @category
		else
			render 'edit'
		end
	end

	def destroy
		@category = Category.find(params[:id])
		@category.destroy

		redirect_to categories_path
	end

	private

	def category_params
		params.require(:category).permit(:name)
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
	<% if @category.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@category.errors.count, "error") %> prohibited
				this article from being saved:
			</h2>
			<ul>
				<% @category.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.submit class: "btn btn-primary" %>
	</div>
<% end %>

<%= link_to 'Back', categories_path, class: "btn btn-default" %>

app/views/categories/edit.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<h1>Edit Category Page</h1>

	<%= render 'form' %>
</div>

app/views/categories/index.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<h1>Categories Page</h1>
	<%= link_to 'Add category', new_category_path, class: "btn btn-primary btn-add" %>
	<table class="table table-bordered">
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Actions</th>
		</tr>
		<% @categories.each do |category| %>
			<tr>
				<td><%= category.id %></td>
				<td><%= category.name %></td>
				<td>
					<%= link_to 'Show', category_path(category), class: "btn btn-success" %>
					<%= link_to 'Edit', edit_category_path(category), class: "btn btn-info" %>
					<%= link_to 'Delete', category_path(category), class: "btn btn-danger",
						method: :delete,
						data: { confirm: 'Are you sure you want to delete?' } %>
				</td>
			</tr>
		<% end %>
	</table>
</div>

app/views/categories/new.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<h1>Add Category Page</h1>

	<%= render 'form' %>
</div>

app/views/categories/show.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<h1>Category Page</h1>
	<table class="table table-bordered">
		<tr>
			<th>#</th>
			<td><%= @category.id %></td>
		</tr>
		<tr>
			<th>Name</th>
			<td><%= @category.name %></td>
		</tr>
		<tr>
			<th>Created At</th>
			<td><%= @category.created_at %></td>
		</tr>
		<tr>
			<th>Updated at</th>
			<td><%= @category.updated_at %></td>
		</tr>
	</table>
	
	<h3>Sub Categories</h3>

	<%= link_to "Add Sub Category", new_category_sub_category_path(@category), class: "btn btn-primary btn-add" %>

	<table class="table table-bordered">
		<tr>
			<th>#</th>
			<th>Name</th>
			<th>Actions</th>
		</tr>
		<% @category.sub_categories.each do |sub_category| %>
			<tr>
				<td><%= sub_category.id %></td>
				<td><%= sub_category.name %></td>
				<td>
					<%= link_to 'Show', category_sub_category_path(@category, sub_category),class: "btn btn-success"%>
					<%= link_to 'Edit', edit_category_sub_category_path(@category, sub_category), class: "btn btn-info" %>
					<%= link_to 'Delete', category_sub_category_path(@category, sub_category), class: "btn btn-danger",
						method: :delete, 
						data: { confirm: 'Are you sure you want to delete?' }%></td>
			</tr>
		<% end %>
	</table>

	<%= link_to 'Back', categories_path, class: "btn btn-default" %>
	<%= link_to 'Edit', edit_category_path(@category), class: "btn btn-info" %>
</div>