config/routes.rb
Rails.application.routes.draw do

  root 'main#view'

  scope '/admin' do
    resources :categories do
      resources :sub_categories, path: '/subcategories' do
        resources :sub_sub_categories, path: '/subsubcategories' do
          resources :products
        end
      end
    end
  end

  get '(/:cat(/:subcat(/:subsubcat)))' => 'main#view'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
	# Associations
	belongs_to :sub_sub_category
	has_attached_file :photo

	# Validations
	validates :name, :description, :price, :photo, presence: true
	validates :name, length: { in: 3..25 }
	validates :name, uniqueness: true
	validates :price, format: { with: /\A\d+(?:\.\d{0,2})?\z/ }, numericality: { greater_than: 0 }
	validates_attachment_content_type :photo, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@sub_sub_category = SubSubCategory.find(params[:sub_sub_category_id])
		@products = @sub_sub_category.products
	end

	def show
		@sub_sub_category = SubSubCategory.find(params[:sub_sub_category_id])
		@sub_category = @sub_sub_category.sub_category
		@category = @sub_category.category
		@product = Product.find(params[:id])
	end

	def new
		@sub_sub_category = SubSubCategory.find(params[:sub_sub_category_id])
		@sub_category = @sub_sub_category.sub_category
		@category = @sub_category.category
		@product = @sub_sub_category.products.new
	end

	def create
		@sub_sub_category = SubSubCategory.find(params[:sub_sub_category_id])
		@sub_category = @sub_sub_category.sub_category
		@category = @sub_category.category
		@product = @sub_sub_category.products.new(product_params)

		if @product.save
			redirect_to category_sub_category_sub_sub_category_products_path(@category, @sub_category, @sub_sub_category)
		else
			render 'new'
		end
	end

	def edit
		@sub_sub_category = SubSubCategory.find(params[:sub_sub_category_id])
		@sub_category = @sub_sub_category.sub_category
		@category = @sub_category.category
		@product = Product.find(params[:id])
	end

	def update
		@sub_sub_category = SubSubCategory.find(params[:sub_sub_category_id])
		@sub_category = @sub_sub_category.sub_category
		@category = @sub_category.category
		@product = Product.find(params[:id])

		if @product.update(product_params)
			redirect_to category_sub_category_sub_sub_category_products_path(@category, @sub_category, @sub_sub_category)
		else
			render 'edit'
		end
	end

	def destroy
		@product = Product.find(params[:id])
		@sub_sub_category = SubSubCategory.find(params[:sub_sub_category_id])
		@sub_category = @sub_sub_category.sub_category
		@category = @sub_category.category
		@product.destroy

		redirect_to category_sub_category_sub_sub_category_products_path(@category, @sub_category, @sub_sub_category)
	end

	private

	def product_params
		params.require(:product).permit(:name, :description, :price, :photo)
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for [@category, @sub_category, @sub_sub_category, @product] do |f| %>
	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@product.errors.count, "error") %> prohibited
				this article from being saved:
			</h2>
			<ul>
				<% @product.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :description %>
		<%= f.text_area :description, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :price %>
		<%= f.number_field :price, step: 0.01, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.file_field :photo %>
	</div>

	<div class="form-group">
		<%= f.submit %>
	</div>
<% end %>

<%= link_to 'Back', category_sub_category_sub_sub_category_products_path(@category, @sub_category, @sub_sub_category), class: "btn btn-default" %>

app/views/products/edit.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<h1>Edit product Page</h1>
	<%= render 'form' %>
</div>

app/views/products/index.html.erb
<% sub_category =  @sub_sub_category.sub_category %>
<% category =  sub_category.category %>

<%= render 'layouts/header' %>

<div class="container">
	<h1>Product page of <%= @sub_sub_category.name %></h1>
	<%= link_to 'Add product', new_category_sub_category_sub_sub_category_product_path(category, sub_category, @sub_sub_category), class: "btn btn-primary btn-add" %>

	<table class="table table-bordered">
		<tr>
			<th>#</th>
			<th>Photo</th>
			<th>Name</th>
			<th>Description</th>
			<th>Price</th>
			<th>Actions</th>
		</tr>
		<% @products.each do |product| %>
			<tr>
				<td><%= product.id %></td>
				<td><%= image_tag product.photo.url, height: '135', width: '135' %></td>
				<td><%= product.name %></td>
				<td><%= product.description %></td>
				<td><%= number_to_currency product.price %></td>
				<td>
					<%= link_to 'Show',category_sub_category_sub_sub_category_product_path(category, sub_category, @sub_sub_category, product), class: "btn btn-success" %>
					<%= link_to 'Edit', edit_category_sub_category_sub_sub_category_product_path(category, sub_category, @sub_sub_category, product), class: "btn btn-info" %>
					<%= link_to 'Delete', category_sub_category_sub_sub_category_product_path(category, sub_category, @sub_sub_category, product), class: "btn btn-danger",method: :delete,
						data: { confirm: 'Are you sure you want to delete?' } %></td>
			</tr>
		<% end %>
	</table>
	
	<%= link_to 'Back', category_sub_category_path(sub_category.category, sub_category), class: "btn btn-default" %>
</div>

app/views/products/new.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<h1>New product Page</h1>
	<%= render 'form' %>
</div>

app/views/products/show.html.erb
<%= render 'layouts/header' %>

<div class="container">
	<h1>Product Page</h1>
	
	<table class="table table-bordered">
		<tr>
			<th>#</th>
			<td><%= @product.id %></td>
		</tr>
		<tr>
			<th>Photo</th>
			<td><%= image_tag @product.photo.url, height: '135', width: '135' %></td>
		</tr>
		<tr>
			<th>Name</th>
			<td><%= @product.name %></td>
		</tr>
		<tr>
			<th>Description</th>
			<td><%= @product.description %></td>
		</tr>
		<tr>
			<th>Created At</th>
			<td><%= @product.created_at %></td>
		</tr>
		<tr>
			<th>Updated at</th>
			<td><%= @product.updated_at %></td>
		</tr>
	</table>

	<%= link_to 'Back', category_sub_category_sub_sub_category_products_path(@category, @sub_category, @sub_sub_category), class: "btn btn-default" %>
	<%= link_to 'Edit', edit_category_sub_category_sub_sub_category_product_path(@category, @sub_category, @sub_sub_category, @product), class: "btn btn-info" %>
</div>